spring:
  application:
    name: afripass

  devtools:
    restart:
      enabled: false

  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://postgres:5432/afripass
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

  redis:
    host: ${REDIS_HOST}
    port: 6379

  jpa:
    properties:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

stripe:
  secret-key: ${STRIPE_SECRET_KEY}

logging:
 level:
  org.springframework.security: DEBUG

server:
  port: 8080